= Walkthrough 2
© 2014 Farata Systems LLC. <training@faratasystems.com>

:icons: font
:last-update-label!:
:sectanchors:
:idprefix:
:numbered!:
:source-highlighter: highlightjs


////
* All the resources are added
* Explain structure
* Explain DI
* Explain how to define classes in JS
* Explain controllerAs
* Explain ngSrc
* Explain expressions vs ng-bind
////

== Steps

. Use `walkthroughs/w2` directory from the provided handouts as the starting point for the walkthrough.

. Open `scripts/app.js` file
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` directive create new AngularJS module with name `auction`. It will your main application module:
+
[source,js]
----
(function () {
  'use strict';

  angular.module('auction', []); <1>
}());
----
<1> Notice how we provide the second argument to the `module()` function to actually create the module, not to get an existing one.

. Open `scripts/controller/HomeController.js` file
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` directive define constructor-function `HomeController` with a single parameter `productService`:
+
[source,js]
----
var HomeController = function (productService) {
};
----

.. Inside the constructor function save value of `this` into a local variable `_this`:
+
[source,js]
----
var HomeController = function (productService) {
  var _this = this;
};
----

.. Create a property `products` on the `_this` object. Initialize it with empty array:
+
[source,js]
----
_this.products = [];
----

.. Invoke `getFeaturedProducts()` method of the `productService`, inside `then` callback initialize `products` property created on the previous step with the data received from the service.
+
[source,js]
----
productService.getFeaturedProducts()
    .then(function (data) { _this.products = data; });
----

.. Outside `HomeController` constructor function, initialize `$inject` property of the `HomeController` with an array with single dependency - `ProductService`:
+
[source,js]
----
HomeController.$inject = ['ProductService']; <1>
----
<1> `$inject` - is the way we ask AngularJS to inject registered dependencies into our constructor function.

.. Register `HomeController` inside Angular's DI container using `controller()` method:
+
[source,js]
----
angular.module('auction').controller('HomeController', HomeController);
----

. Open `scripts/controller/SearchController.js`. Repeat the same steps you did for the `HomeController` to define `SearchController`, but instead of invoking `getProducts()` method (step 3F) invoke `find()` method:
+
[source,js]
----
productService.find()
    .then(function (data) { _this.products = data; });
----


. Open `scripts/service/ProductService.js` file
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` directive define constructor-function `ProductService` with a single parameter `$http`:
+
[source,js]
----
var ProductService = function ($http) {
};
----

.. Create property `$http` on the `this` object. Initialize it with `$http` service. This way you'll make it available for other `ProductService` methods:
+
[source,js]
----
var ProductService = function ($http) {
  this.$http = $http;
};
----

.. Initialize `ProductService`'s prototype with an object literal. Inside the object define two properties and initialize them with anonymous functions. This way we declare instance methods:
+
[source,js]
----
ProductService.prototype = {
  getProducts: function () {},
  find: function () {}
};
----

.. Inside `getProducts()` use `$http` service available as `$http` property on `this` object, to make HTTP GET request to the static JSON file `products-featured.json`. Inside `then` callback unwrap products from HTTP response object and return them from the callback:
+
[source,js]
----
getProducts: function () {
  return this.$http.get('/data/products-featured.json')
      .then(function (resp) { return resp.data; });
}
----

.. Do the same thing as on the previous step for `find()` function, but make HTTP GET request to `products-search.json` file:
+
[source,js]
----
find: function () {
  return this.$http.get('/data/products-search.json')
      .then(function (resp) { return resp.data; });
}
----

.. Initialize `$inject` property of the `ProductService` constructor function with an array with single dependency - `$http` service:
+
[source,js]
----
ProductService.$inject = ['$http'];
----

.. Register `ProductService` inside Angular's DI container using `service()` method:
+
[source,js]
----
angular.module('auction').service('ProductService', ProductService);
----


. Open `index.html` file
[style="upperalpha"]
.. Bootstrap AngularJS application using `ng-app` directive:
+
[source,html]
----
<html ng-app="auction"> <1>
----
<1> Notice how we initialize the directive with the `auction` value. It *must* be the same as the name you use to create main application module.

.. Using `ng-init` directive create a new variable `currentView` on the root scope and initialize it with `'home'` value:
+
[source,html]
----
<div class="row" ng-init="currentView = 'home'"> <1>
----
<1> `ng-init` is not a best practice, use only for quick prototyping.

.. Using `ng-include` directive, specify path to the currently displayed view for the `div`. Inside the expression use `currentView` variable to always show actual page:
+
[source,html]
----
<div class="row" ng-init="currentView = 'home'" ng-include="'views/' + currentView + '.html'">
----

.. Add navigation to the Home page, by defining `ng-click` directive for the brand name link:
+
[source,html]
----
<a class="navbar-brand" ng-click="currentView = 'home'">ABC Auction</a>
----

.. Add navigation to the Search page, by defining `ng-click` directive for the Search button:
+
[source,html]
----
<a ng-click="currentView = 'search'" class="btn btn-default">Search</a>
----

. Open `veiws/home.html` file
[style="upperalpha"]
.. Define `ng-controller` directive for the top level div. Initialize it with `HomeController`:
+
[source,html]
----
<div ng-controller="HomeController as ctrl"> <1>
----
<1> Notice how we use _controller as_ feature to expose all controller's instance  fields and methods on the scope.

.. Using `ng-repeat` iterate through the products available on the `ctrl`:
+
[source,html]
----
<li class="col-md-4" ng-repeat="product in ctrl.products"> <1>
----
<1> `ng-repeat` creates a new _child scope_, so within the `ng-repeat` block you can use `product` variable to reference current product.

.. Using `ng-src` directive define path to the current product's thumbnail:
+
[source,html]
----
<img ng-src="images/{{ product.thumb }}" alt="" class="img-responsive"> <1>
----
<1> Unlike `src`, `ng-src` prevents making HTTP request till the data-binding expression is resolved.

.. Using data-binding expressions display title and description of the current product:
+
[source,html]
----
<h2><a>{{ product.title }}</a></h2>
<p>{{ product.description }}</p>
----

. Open `views/search.html` file
[style="upperalpha"]
.. Define `ng-controller` directive for the top level div. Initialize it with `SearchController`:
+
[source,html]
----
<div ng-controller="SearchController as ctrl">
----

.. Using `ng-repeat` iterate through the products available on the `ctrl`:
+
[source,html]
----
<li class="col-md-4" ng-repeat="product in ctrl.products">
----

.. Using `ng-src` directive define path to the current product's thumbnail:
+
[source,html]
----
<img ng-src="images/{{ product.thumb }}" alt="" class="img-responsive">
----

.. Using data-binding expressions display title and description of the current product:
+
[source,html]
----
<h2><a>{{ product.title }}</a></h2>
<p>{{ product.description }}</p>
----

.. Using data-binding expressions display time left, watchers and price of the current product:
+
[source,html]
----
<span class="badge">{{ product.timeleft }} hour left</span>
----
+
[source,html]
----
<span class="badge">
  <span class="glyphicon glyphicon-eye-open"></span> {{ product.watchers }}
</span>
----
+
[source,html]
----
<span class="badge">
  {{ product.price | currency }} <1>
</span>
----
<1> Notice how we use built-in `currency` filter to represent price in a human-readable way.
