= Unit 4. Walkthrough 1.
© 2014 Farata Systems LLC. <training@faratasystems.com>

:icons: font
:last-update-label!:
:sectanchors:
:idprefix:
:numbered!:
:source-highlighter: coderay


== Summary

In this walkthrough you will implement the search form directive with one custom reusable component - price range component.

== Steps

=== Part 1: Search Form

. Use `walkthroughs/w1` directory from the provided handouts as the starting point for the walkthrough.

. Open `bower.json` file. Add `"bootstrap-datepicker": "^1.3.0"` dependency to the `dependencies` section.

. Run `bower install` and `grunt wiredep` in the console to install newly added dependency to the app.

. Create `app/scripts/directive/SearchFormDirective.js` file, and open it.
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` declare a factory function that we will use to create the directive. Name it `searchFormDirectiveFactory`:
+
[source,js]
----
var searchFormDirectiveFactory = function () {};
----

.. Return a JavaScript object literal from `searchFormDirectiveFactory` function with following properties initialized: `scope`, `restrict` and `templateUrl`:
+
[source,js]
----
var searchFormDirectiveFactory = function () {
  return {
    scope: false,
    restrict: 'E',
    templateUrl: 'views/partial/SearchFormDirective.html'
  };
};
----

.. Register the directive inside AngularJS DI container invoking `directive()` method available on the application nodule:
+
[source,js]
----
angular.module('auction').directive('auctionSearchForm', searchFormDirectiveFactory);
----

. Create `app/views/partial/SearchFormDirective.html` file and open it.
[style="upperalpha"]
.. Add HTML markup for the search form:
+
[source,html]
----
<div>
  <div class="col-xs-12 col-md-4">
    <div class="row form-group">
      <div class="col-xs-12 col-sm-6 col-md-12">
        <label class="control-label">Product</label>
        <input type="text" class="form-control" placeholder="Product title">
      </div>
      <div class="col-xs-12 col-sm-6 col-md-12">
        <label class="control-label">&nbsp;</label>
        <select class="form-control">
          <option>Category</option>
          <option>Category 1</option>
          <option>Category 2</option>
          <option>Category 3</option>
        </select>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-8">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <!-- PLACEHOLDER FOR PRICE RANGE COMPONENT -->
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="row">
          <div class="col-xs-12">
            <label class="control-label">Max Auction Close Day</label>

            <div class="input-group">
              <!-- THE INPUT BELOW WILL BECOME A CALENDAR ONCE WE IMPLEMENT DATEPICKER DIRECTIVE -->
              <input data-date-format="mm/dd/yyyy" class="form-control" value="08/17/2014">
              <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
            </div>
          </div>
          <div class="col-xs-12">
            <label class="control-label">&nbsp;</label><br>

            <form class="form-horizontal" role="form">
              <div class="form-group">
                <div class="col-xs-8">
                  <label class="control-label">Number of Bids</label>
                </div>
                <div class="col-xs-4">
                  <input type="number" class="form-control" value="3">
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-md-4 col-md-offset-4">
    <br>
    <button class="btn btn-default btn-block btn-primary">Find more</button>
  </div>
</div>
----

. Open `app/index.html` file. Scroll at the bottom of the file. Add `<script>` tag for the directive's JavaScript file:
+
[source,html]
----
<script src="scripts/directive/SearchFormDirective.js"></script>
----

. Open `app/views/search.html` file and add `<auction-search-form>` element at the very top of the file,
right after opening top-level `<div>` tag:
+
[source,html]
----
<div>
  <div class="row well">
    <auction-search-form></auction-search-form>
  </div>
  <!-- Rest of the page below -->
----

. Open `app/views/product.html` file and add `<auction-search-form>` right after `Find more` and close buttons are defined. Add `ng-show="ctrl.isSearchFormVisible"` directive to show/hide the form when user clicks the button:
+
[source,html]
----
<auction-search-form ng-show="ctrl.isSearchFormVisible"></auction-search-form>
----


=== Part 2: Datepicker Directive

. Create `app/scripts/directive/DatepickerDirective.js` file, and open it.
[style="upperalpha"]
.. Define self-executable anonymous function:
+
[source,js]
----
(function () {

}());
----

.. Inside the function declare `use strict` directive:
+
[source,js]
----
(function () {
  'use strict';
}());
----

.. Right after `'use strict';` declare a factory function that we will use to create the directive. Name it `datepickerDirectiveFactory`:
+
[source,js]
----
var datepickerDirectiveFactory = function () {};
----

.. Return a JavaScript object literal from `datepickerDirectiveFactory` function with following properties initialized: `scope`, `restrict` and `link`:
+
[source,js]
----
var datepickerDirectiveFactory = function () {
  return {
    scope: false,
    restrict: 'A', <1>
    link: function (scope, element) {
      element.datepicker(); <2>
    }
  };
};
----
<1> Notice we allow to use the directive only as an attribute
<2> Inside link function we initialize the component using `datepicker()` method added by `bootstrap-datepicker` package.

.. Register the directive inside AngularJS DI container invoking `directive()` method available on the application nodule:
+
[source,js]
----
angular.module('auction').directive('auctionDatepicker', datepickerDirectiveFactory);
----
